#!/bin/bash


#################################################
### save values for later in a file like this ###
#################################################


## Output directory ##
OUTDIRDEF="./source/"

## Host defaults ##
HOSTDEF="BitBucket"
BRANCHDEF="master"
TYPE="zip"  # BitBucket default is zip for git archive!

## Repo Name ##
REPODEF="ml-mlearning-leaflet"

## Repo Owner ##
OWNERDEF="CornellLabofOrnithology"

## Host defaults ##
HOSTDEF="BitBucket"
BRANCHDEF="master"

## BitBucket- git Username & git password or read token ##
USERDEF="<YourGitUsername>"
TOKENDEF="<YourGitPassphrase>"
