import * as audio_loader from './audio_loading_utils';
import * as audio_utils from './audio_utils';
import * as spectrogram_utils from './spectrogram_utils';
import * as audio_model from './audio_model';
import * as ui_utils from './ui_utils';
declare const tf: any;
export { tf };
import AudioRecorder from 'audio-recorder-polyfill';
export { AudioRecorder };
export { audio_model, audio_loader, audio_utils, spectrogram_utils, ui_utils };
export declare const log: (msg: string, prefix?: string) => void;
